### ISSUE TITLE
Change some of incorrect links

### ISSUE THREAD

**Issue by MohamedAli00949** [Seth0x41/awesome-egypt#1]
Hi @Seth0x41 ,

Thank you for this effort, but I have noticed some incorrect links on the lists I will mention below.

- **At Podcasts list**, the link of *Tech and Coffe* is the same link of *Ahmed Elemam* podcast.
- **At Youtube channel list**, the link of *محمد يحيى* is the same link of *درة الاكواد لابن حماد* channel.

That's all about these links, Thanks again for your effort to collect, organize, and write all these things to benefit others in our community.

**Comment by Seth0x41** [comment]
Hello @MohamedAli00949 
Thank you for your kind words and for pointing out the incorrect links. They have been fixed now.
